#!/usr/bin/env bb
;; World Hopping: Navigate between AI agent worlds (amp, claude, codex)
;; Preserves dynamics/context across transitions via invariants

(require '[babashka.fs :as fs]
         '[clojure.string :as str]
         '[cheshire.core :as json]
         '[clojure.edn :as edn])

;;; ============================================================================
;;; World Definitions
;;; ============================================================================

(def WORLDS
  {:amp {:seed 0xA3F
         :name "Amp"
         :config-path "~/.config/amp"
         :history-path "~/.amp/threads"
         :model-env "AMP_MODEL"
         :capabilities #{:tools :mcp :skills :oracle :threads}
         :api :anthropic}
   
   :claude {:seed 0xC1A
            :name "Claude Code"
            :config-path "~/.claude"
            :history-path "~/.claude/projects"
            :model-env "ANTHROPIC_API_KEY"
            :capabilities #{:tools :mcp :skills :artifacts}
            :api :anthropic}
   
   :codex {:seed 0xC0D
           :name "Codex (OpenAI)"
           :config-path "~/.codex"
           :history-path "~/.codex/history"
           :model-env "OPENAI_API_KEY"
           :capabilities #{:tools :sandbox :apply}
           :api :openai}
   
   :codex-mlx {:seed 0xC07
               :name "Codex-MLX (Local)"
               :config-path "~/.codex"
               :history-path "~/.codex/history"
               :model-env "OPENAI_BASE_URL"
               :base-url "http://localhost:8080/v1"
               :capabilities #{:tools :sandbox :apply :local}
               :api :openai-local}})

;;; ============================================================================
;;; Invariants: What persists across world transitions
;;; ============================================================================

(def INVARIANTS-PATH (fs/expand-home "~/.topos/world_invariants.edn"))

(defn load-invariants []
  (if (fs/exists? INVARIANTS-PATH)
    (edn/read-string (slurp (str INVARIANTS-PATH)))
    {:skills []
     :context {}
     :history-refs []
     :preferences {}}))

(defn save-invariants! [inv]
  (spit (str INVARIANTS-PATH) (pr-str inv)))

(defn extract-invariants-from-world [world-key]
  (let [world (get WORLDS world-key)
        config-path (fs/expand-home (:config-path world))]
    {:world world-key
     :timestamp (str (java.time.Instant/now))
     :skills (when (fs/exists? (fs/path config-path "skills"))
               (->> (fs/list-dir (fs/path config-path "skills"))
                    (filter fs/directory?)
                    (mapv #(str (fs/file-name %)))
                    (take 20)))
     :has-mcp? (fs/exists? (fs/path config-path ".mcp.json"))
     :has-agents? (fs/exists? (fs/path config-path "AGENTS.md"))}))

;;; ============================================================================
;;; World Distance (Triangle Inequality)
;;; ============================================================================

(defn hamming-distance [a b]
  (Long/bitCount (bit-xor a b)))

(defn capability-overlap [w1 w2]
  (let [c1 (:capabilities w1)
        c2 (:capabilities w2)
        shared (count (clojure.set/intersection c1 c2))
        total (count (clojure.set/union c1 c2))]
    (if (zero? total) 0.0 (/ shared total))))

(defn world-distance [w1-key w2-key]
  (let [w1 (get WORLDS w1-key)
        w2 (get WORLDS w2-key)]
    (if (= w1-key w2-key)
      0.0
      (let [seed-dist (hamming-distance (:seed w1) (:seed w2))
            api-dist (if (= (:api w1) (:api w2)) 0 5)
            cap-dist (* 10 (- 1 (capability-overlap w1 w2)))]
        (Math/sqrt (+ (* seed-dist seed-dist) 
                      (* api-dist api-dist) 
                      (* cap-dist cap-dist)))))))

(defn valid-triangle? [w1 w2 w3]
  (let [d12 (world-distance w1 w2)
        d23 (world-distance w2 w3)
        d13 (world-distance w1 w3)]
    (<= d13 (+ d12 d23))))

;;; ============================================================================
;;; Codex MLX Configuration
;;; ============================================================================

(defn configure-codex-mlx! []
  (let [codex-dir (fs/expand-home "~/.codex")
        config-toml (fs/path codex-dir "config.toml")
        config-mlx (fs/path codex-dir "config.mlx.toml")
        env-file (fs/path codex-dir "env")]
    
    ;; Ensure directory exists
    (fs/create-dirs codex-dir)
    
    ;; Backup existing config
    (when (fs/exists? config-toml)
      (fs/copy config-toml (fs/path codex-dir "config.backup.toml") 
               {:replace-existing true}))
    
    ;; Create MLX-specific config
    (spit (str config-mlx)
          "# Codex MLX Configuration (local model)
# Generated by world_hop.bb
# Switch with: cp ~/.codex/config.mlx.toml ~/.codex/config.toml

model = \"default\"
provider = \"openai\"

[api]
base_url = \"http://localhost:8080/v1\"

[projects.\"/Users/alice\"]
trust_level = \"trusted\"

[features]
unified_exec = true
shell_snapshot = true
")
    
    ;; Create/update env file for MLX
    (spit (str env-file)
          "# Codex MLX Configuration
# Source this before running codex: source ~/.codex/env
export OPENAI_BASE_URL=http://localhost:8080/v1
export OPENAI_API_KEY=mlx-local
")
    
    ;; Create a launcher script
    (let [launcher (fs/path codex-dir "codex-mlx")]
      (spit (str launcher)
            "#!/bin/bash
# Launch Codex with local MLX model
export OPENAI_BASE_URL=http://localhost:8080/v1
export OPENAI_API_KEY=mlx-local
exec codex \"$@\"
")
      (fs/set-posix-file-permissions launcher "rwxr-xr-x"))
    
    (println "✓ Created ~/.codex/config.mlx.toml")
    (println "✓ Created ~/.codex/codex-mlx launcher")
    (println "✓ Created ~/.codex/env")
    {:configured true 
     :launcher (str (fs/path codex-dir "codex-mlx"))
     :env (str env-file)}))

;;; ============================================================================
;;; World Hopping
;;; ============================================================================

(defn hop! [from-key to-key & {:keys [preserve-context?] :or {preserve-context? true}}]
  (println (format "\n=== World Hop: %s → %s ===" 
                   (name from-key) (name to-key)))
  
  (let [from (get WORLDS from-key)
        to (get WORLDS to-key)
        distance (world-distance from-key to-key)]
    
    (println (format "Distance: %.2f" distance))
    (println (format "From: %s (%s)" (:name from) (name (:api from))))
    (println (format "To: %s (%s)" (:name to) (name (:api to))))
    
    ;; Extract invariants from source world
    (when preserve-context?
      (let [inv (extract-invariants-from-world from-key)
            current (load-invariants)]
        (save-invariants! (assoc current 
                                 :last-hop {:from from-key :to to-key :at (:timestamp inv)}
                                 :source-context inv))
        (println "✓ Preserved context from" (name from-key))))
    
    ;; Special handling for codex-mlx
    (when (= to-key :codex-mlx)
      (configure-codex-mlx!))
    
    ;; Show capability delta
    (let [gained (clojure.set/difference (:capabilities to) (:capabilities from))
          lost (clojure.set/difference (:capabilities from) (:capabilities to))]
      (when (seq gained)
        (println "Gained:" (str/join ", " (map name gained))))
      (when (seq lost)
        (println "Lost:" (str/join ", " (map name lost)))))
    
    {:from from-key
     :to to-key
     :distance distance
     :success true}))

;;; ============================================================================
;;; CLI
;;; ============================================================================

(defn show-worlds []
  (println "\n╔═══════════════════════════════════════════╗")
  (println "║   Available Worlds                        ║")
  (println "╚═══════════════════════════════════════════╝\n")
  (doseq [[k w] WORLDS]
    (println (format "%-12s %s" (name k) (:name w)))
    (println (format "             API: %s" (name (:api w))))
    (println (format "             Caps: %s" (str/join ", " (map name (:capabilities w)))))
    (println)))

(defn show-distances []
  (println "\n=== World Distance Matrix ===\n")
  (let [keys [:amp :claude :codex :codex-mlx]]
    (print "            ")
    (doseq [k keys] (print (format "%12s" (name k))))
    (println)
    (doseq [k1 keys]
      (print (format "%-12s" (name k1)))
      (doseq [k2 keys]
        (print (format "%12.1f" (world-distance k1 k2))))
      (println))))

(defn -main [& args]
  (let [cmd (first args)]
    (case cmd
      "list" (show-worlds)
      "distances" (show-distances)
      "hop" (let [from (keyword (second args))
                  to (keyword (nth args 2))]
              (hop! from to))
      "mlx" (do
              (println "Configuring Codex for local MLX...")
              (configure-codex-mlx!)
              (println "\nTo use:")
              (println "  1. Start MLX: just mlx-server")
              (println "  2. Source env: source ~/.codex/env")
              (println "  3. Run codex normally"))
      "invariants" (println (pr-str (load-invariants)))
      ;; Default
      (do
        (println "Usage: world_hop.bb <command>")
        (println "")
        (println "Commands:")
        (println "  list        Show available worlds")
        (println "  distances   Show distance matrix")
        (println "  hop <from> <to>  Hop between worlds")
        (println "  mlx         Configure Codex for local MLX")
        (println "  invariants  Show preserved invariants")))))

(apply -main *command-line-args*)
